window.WEDDING_CONFIG = {
  locale: "hy-AM",
  googleMapsApiKey: "",
  pageTitle: "Հարսանիքի հրավեր",
  backgroundImage: "hills.jpeg",
  coupleLine: "Մերուժան և Լուիզա",
  tagline: "",
  heroSubline: "Հարսանյաց հրավեր",
  weddingDateISO: "2026-06-19T14:30:00",
  heroDateLine: "Ուրբաթ, 19 հունիսի, 2026 թ.",
  welcomeInviteLine:
    "Սիրով հրավիրում ենք կիսելու մեր կյանքի ամենակարևոր և հիշարժան օրը։",
  defaultGuestGreeting: "Հարգելի հյուր,",
  guestGreetingTemplate: "Հարգելի {name},",
  church: {
    title: "Պսակադրություն",
    intro: "Սուրբ Մարիամ Աստվածածին եկեղեցի",
    name: "Սուրբ Մարիամ Աստվածածին եկեղեցի",
    time: "19 հունիսի, 2026 - 14:30",
    addressLines: [],
    lat: 40.1868101,
    lng: 44.5409983,
    mapLabel: "Եկեղեցի",
    mapSearchQuery: "Սուրբ Մարիամ Աստվածածին եկեղեցի, Երևան",
    mapsAppUrl: "https://maps.app.goo.gl/jsE2xnfZWQrMmbPZ8",
    googleMapsEmbedUrl:
      "https://www.google.com/maps?q=40.1868101,44.5409983&z=17&hl=hy&output=embed",
  },
  reception: {
    title: "Հանդիսություն",
    intro: "Villa ռեստորանային համալիր",
    name: "Villa ռեստորանային համալիր",
    time: "19 հունիսի, 2026 - 17:30",
    addressLines: [],
    lat: 40.1864396,
    lng: 44.6034511,
    mapLabel: "Ռեստորան",
    mapSearchQuery: "Villa ռեստորանային համալիր, Երևան",
    mapsAppUrl: "https://maps.app.goo.gl/NtZxgczz6rYR7QQ98",
    googleMapsEmbedUrl:
      "https://www.google.com/maps?q=40.1864396,44.6034511&z=17&hl=hy&output=embed",
  },
  closingLine: "Սիրով սպասում ենք։",
  rsvpIntro: "Հաստատման համար զանգահարեք կամ գրեք։",
  rsvpEmail: "l522arch@gmail.com",
  contact: [
    { label: "Մերուժան", phone: "+374 91 613 919" },
    { label: "Լուիզա", phone: "+374 94 311 309" },
  ],
  strings: {
    skipToContent: "Անցնել բովանդակությանը",
    monogramAria: "Սկիզբ",
    navAria: "Բաժիններ",
    navWelcome: "Հրավեր",
    navDetails: "Տեղ ու ժամ",
    navMaps: "Քարտեզ",
    countdownAria: "Մնացել է մինչև հարսանիքը",
    countdownDay: "Օր",
    countdownHour: "Ժամ",
    countdownMinute: "Րոպե",
    countdownSecond: "Վրկ",
    countdownDone: "Այսօր է։",
    sectionInvitation: "Հրավեր",
    sectionWhenWhere: "Տեղ ու ժամ",
    sectionDirections: "Ինչպես հասնել",
    footerQuestions: "Կապ",
    mapChurchAria: "Եկեղեցու քարտեզ",
    mapReceptionAria: "Ռեստորանի քարտեզ",
    mapOpenExternal: "Բացել Google Maps-ում",
    introVenuePrefix: "",
    rsvpFormLead: "Խնդրում ենք հաստատել Ձեր ներկայությունը՝",
    rsvpFullName: "Անուն Ազգանուն",
    rsvpAttendYes: "Սիրով կմասնակցենք",
    rsvpAttendNo: "Ցավոք, չենք կարող ներկա լինել",
    rsvpGuestCount: "Հյուրերի ընդհանուր թիվ",
    rsvpComment: "Մեկնաբանություն",
    rsvpSubmit: "Ուղարկել",
    rsvpErrorName: "Լրացրեք անունը և ազգանունը։",
    rsvpErrorAttendance: "Ընտրեք մասնակցության տարբերակներից մեկը։",
    rsvpErrorEmail: "RSVP-ի համար config.js-ում լրացրեք rsvpEmail (էլ. հասցե)։",
    rsvpSuccess: "Հաստատումը ուղարկված է։ Շնորհակալություն։",
    rsvpSendError:
      "Չհաջողվեց ուղարկել։ Խնդրում ենք կրկին փորձել կամ զանգահարել մեզ։",
    rsvpLocalFile:
      "Ձևը չի աշխատում, երբ էջը բացված է ֆայլից (file://)։ Բացեք կայքը HTTP սերվերի վրա (օր․ GitHub Pages, Netlify, կամ տեղում՝ npx serve)։",
    rsvpAttendanceAria: "Մասնակցություն",
  },
};
